#!/bin/bash
#
#       /etc/rc.d/init.d/softswitch
#
#

# Source function library.
. /etc/init.d/functions

PROG_NAME=SoftSWITCH
PROG_DIR=/home/pub/release/fs106
PID_FILE=$PROG_DIR/run/freeswitch.pid
PROC_NAME=freeswitch
FS_USER=pub
FS_FILE=$PROG_DIR/bin/freeswitch 
FS_HOME=$PROG_DIR
LOCK_FILE=$PROG_DIR/run/freeswitch.lock
FREESWITCH_ARGS="-nc"
RETVAL=0

# <define any local shell functions used by the code that follows>

start() {
        echo -n "Starting $PROG_NAME: "
        if [ -e $LOCK_FILE ]; then
            if [ -e $PID_FILE ] && [ -e /proc/`cat $PID_FILE` ]; then
                echo
                echo -n $"$PROG_NAME is already running.";
                failure $"$PROG_NAME is already running.";
                echo
                return 1
            fi
        fi
	cd $FS_HOME
        daemon --user $FS_USER --pidfile $PID_FILE "$FS_FILE $FREESWITCH_ARGS >/dev/null 2>&1"
		echo
		RETVAL=$?
        [ $RETVAL -eq 0 ] && touch $LOCK_FILE;
	echo
        return $RETVAL
}

stop() {
        echo -n "Shutting down $PROG_NAME: "
        if [ ! -e $LOCK_FILE ]; then
            echo
            echo -n $"cannot stop $PROG_NAME: $PROG_NAME is not running."
            failure $"cannot stop $PROG_NAME: $PROG_NAME is not running."
            echo
            return 1;
        fi
	cd $FS_HOME
	$FS_FILE -stop > /dev/null 2>&1
        killproc $PROC_NAME
	RETVAL=$?
	echo
	[ $RETVAL -eq 0 ] &&  rm -f $LOCK_FILE;
        return $RETVAL
}

rhstatus() {
	status $PROC_NAME;
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status $PROC_NAME
	RETVAL=$?
        ;;
    restart)
        stop
        start
        ;;
    reload)
#        <cause the service configuration to be reread, either with
#        kill -HUP or by restarting the daemons, in a manner similar
#        to restart above>
        ;;
    condrestart)
        [ -f $PID_FILE ] && restart || :
	;;
    *)
        echo "Usage: $PROG_NAME {start|stop|status|reload|restart}"
        exit 1
        ;;
esac
exit $RETVAL
